Numpy is a specially designed library for data analysis, mathematical computation etc
Numpy is used to perform operations on arrays 
Faster, less memory

In [2]:
import numpy as np
arr=np.array([1,2,4])
arr

array([1, 2, 4])

In [3]:
nums=[20,30,40,50]
nums+nums

[20, 30, 40, 50, 20, 30, 40, 50]

In [4]:
#see here it performs mathematical operation addition on array
array=np.array([10,20,30,40])
array+array

array([20, 40, 60, 80])

In [5]:
#vectorization means the number 5 is added to each of the element
array+5

array([15, 25, 35, 45])

In [6]:
array*10

array([100, 200, 300, 400])

In [7]:
array/8

array([1.25, 2.5 , 3.75, 5.  ])

In [8]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#reshape is used to convert the dimension of the array
reshaped_arr=a.reshape(3,4)
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#ndim is used to find the dimension of the array
reshaped_arr.ndim

2

In [12]:
print("Print the first row: ",reshaped_arr[0,:])

Print the first row:  [0 1 2 3]


In [13]:
print("Print the first column: ",reshaped_arr[:,0])

Print the first column:  [0 4 8]


In [14]:
print(reshaped_arr[0:2,1:3])

[[1 2]
 [5 6]]


In [26]:
print(sum(reshaped_arr))

[12 15 18 21]


In [28]:
print("sum of the elements in the numpy array: ",np.sum(reshaped_arr))
print("mean of the matrix: ",np.mean(reshaped_arr))
print("median of the matrix: ",np.median(reshaped_arr))
print("variance of the matrix: ",np.var(reshaped_arr))
print("minimum of the array",np.min(reshaped_arr))
print("maximum of the array: ",np.max(reshaped_arr))
print("minimum value index in the array/matrix: ",np.argmin(reshaped_arr))#here it first flattens the array and gives the index
print("max value index in the array: ",np.argmax(reshaped_arr))
print("product of the array: ",np.prod(reshaped_arr))
#also we have many functions like no.any()/np.all() etc.....

sum of the elements in the numpy array:  66
mean of the matrix:  5.5
median of the matrix:  5.5
variance of the matrix:  11.916666666666666
minimum of the array 0
maximum of the array:  11
minimum value index in the array/matrix:  0
max value index in the array:  11
product of the array:  0


In [31]:
#this concept is for getting the rows and cols in a matrix in argmax/argmin
#here we use the unravel function to get the row and col of the min/max ele in the matrix
index=np.argmax(reshaped_arr)
row,col=np.unravel_index(index,reshaped_arr.shape)
print(row,col)

2 3


In [37]:
import random
print(np.random.randint(1,5,5))#start,end,no.of ele

[2 1 1 3 4]
