In [1]:
import numpy as np


In [3]:
# Q-1
marks=[78,85,91,67,88]
new_marks=np.array(marks)
print(new_marks)
print(type(marks))
print(new_marks.shape)

[78 85 91 67 88]
<class 'list'>
(5,)


In [4]:
# Q-2
prices=[120,450,780,220,560]
new_prices=np.array(prices)
print(new_prices)
print(new_prices.ndim)
print(len(new_prices))

[120 450 780 220 560]
1
5


In [5]:
# Q-3
arr=np.array([12,232,53,33,54,34,77,56,88,11])
print(arr.shape)
print(len(arr))
print(type(arr))
print(arr.ndim)

(10,)
10
<class 'numpy.ndarray'>
1


In [6]:
# Q-4
#vectorization concept
salary=np.array([25000,30000,45000,28000])
new_salary=salary+5000
print(new_salary)

[30000 35000 50000 33000]


In [7]:
# Q-5
marks=np.array([67,76,77,98,55])
new_marks=marks+5
print(new_marks)
#using numpy requires less code

[ 72  81  82 103  60]


In [9]:
# Q-6
import time
python_list=list(range(100000))
np_list=np.arange(100000)

start=time.time()
result=[x*2 for x in python_list]
end=time.time()
print("Time taken : ",end-start)
start=time.time()
np_res=np_list*2
end=time.time()
print("time taken by np list : ",end-start)
# numpy operation is faster

Time taken :  0.005342245101928711
time taken by np list :  0.0006330013275146484


In [13]:
# Q-7
py_fruits=[1,2,3,4,5]
np_fruits=np.array([1,2,3,4,5])
# for i in range(len(py_fruits)):
#     py_fruits[i]=py_fruits[i]*2
#     np_fruits=np_fruits*2
py_fruits=[i*2 for i in py_fruits]
np_fruits=np_fruits*2
print(py_fruits)
print(np_fruits)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


In [16]:
# Q-8
stock=[10,20,30,40]
py_stock=[st*2 for st in stock]
np_stock=np.array(stock)*2
print(py_stock)
print(np_stock)

[20, 40, 60, 80]
[20 40 60 80]


In [20]:
# Q-9
exp=[10,20,30,40]
np_exp=np.array(exp)
print(sum(exp))
print(np.sum(np_exp))

100
100


In [22]:
# Q-10
marks = np.array([55,65,75,85,95]) 
print(marks[0])
print(marks[-1])
print(marks[2])

55
95
75


In [24]:
# Q-11
sales = np.array([120,130,140,150,160,170]) 
print(sales[:3])
print(sales[-2:])
print(sales[1:-1])

[120 130 140]
[160 170]
[130 140 150 160]


In [33]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,:])
print(mat[:,1])
print(mat[2,:])

[1 2 3]
[2 5 8]
[7 8 9]


In [37]:
marks = np.array([35,55,72,89,40,91]) 
new_marks=marks[marks>=40]
new_marks

array([55, 72, 89, 40, 91])

In [38]:
salaries=np.array([98989,46646,66767,76543])
new_salaries=salaries[salaries>50000]
new_salaries


array([98989, 66767, 76543])

In [39]:
ratings = np.array([2,5,4,3,5,1]) 
print(ratings[0],ratings[2],ratings[5])

2 4 1


In [43]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([11,12,13,14,15])
print(arr1+arr2)
print(arr1*arr2)
      

[12 14 16 18 20]
[11 24 39 56 75]


In [45]:
savings = np.array([100,200,300,400]) 
print(np.max(savings),np.argmax(savings))
print(np.min(savings),np.argmin(savings))

400 3
100 0


In [53]:
health = np.array([True,True,False,True]) 
print(np.all(health))
print(np.any(health))

False
True
